services:
  # ATM the bulwark auth docker container is not compitible with apple silicion (arm linux)
  # bulwark.auth:
  #   image: "lateflip/bulwark.auth:1.0.0-beta.13" 
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - mongodb
  #     - mailhog
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - '27017:27017'
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025